version: '3.7'

services:
  smartbrain-api:
    container_name: backend
    # image: node:8.11.1
    build: ./
    command: npm start
    working_dir: /usr/src/smartbrain-api
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/smartbrain-api
    